### ISSUE TITLE
Camera size results wrong upon orientation change and video results incorrect.

### ISSUE THREAD

**Issue by ocramot** [WowzaMediaSystems/gocoder-sdk-samples-android#1]
Steps to reproduce:
1 - Open app;
2 - Select 'Stream live video and audio' (I didn't test the other modes, but I assume they have the same problem);
3 - Start a stream, either in portrait or landscape mode;
4 - Change orientation during streaming;
5 - Stop the streaming; 
6 - Keep the actual orientation and start a new streaming;
7 - Check on wowza server, using the test player. The video received is correct only in a square, the rest of the rectangle is repeated. See attached pictures:
![from_portrait_to_landscape](https://cloud.githubusercontent.com/assets/5261731/18053784/67129ea4-6e01-11e6-8c78-e5096688fa04.png)
![from_landscape_to_portrait](https://cloud.githubusercontent.com/assets/5261731/18053787/6d4fa852-6e01-11e6-812d-5ea880149bf4.png)

This does NOT happen if you: 1) start a stream, 2) stop a stream, 3) change orientation, 4) start a new stream. So I suppose that some part of the configuration gets corrupted if you change orientation during streaming. 
I couldn't find where the issue is located. I also tried to reset the WZBroadcastConfig and WZCameraView objects upon the Android's onConfigurationChanged event, but this led me to other errors...

**Comment by robgabbard-wowza** [comment]
Thanks for reporting this issue. We're looking into it now and targeting the fix for a new release that is planned for later this week.

**Comment by ocramot** [comment]
I just realized that you released a new build (version 0259) ten days ago. I was still using the previous release (version 0230). This issue seems to have been resolved in the last build. Sorry if I bothered you.
