### ISSUE TITLE
Can we pause streaming while user goes in background ?

### ISSUE THREAD

**Issue by Sonamgupta2109** [WowzaMediaSystems/gocoder-sdk-samples-android#10]
Currently we tried 
       mWZCameraView.onPause();

This works fine but when user open camera and try to record the video it terminate app. Give mic error. 
I also tried all these option.

           mWZAudioDevice.setAudioEnabled(false);
            mWZAudioDevice.setMuted(true);
            mWZAudioDevice.setAudioPaused(true);
            mWZAudioDevice.stopAudioSampler();

But nothing works. Please help

**Comment by wowza-mbrinker** [comment]
It's not currently possible to pause an ongoing broadcast on Android while the app is in the background. This is in our product roadmap, but there's no timeline yet.
