### ISSUE TITLE
FaceDetectionListener not working

### ISSUE THREAD

**Issue by harisazam** [WowzaMediaSystems/gocoder-sdk-samples-android#11]
Camera.FaceDetectionListener (FaceActivity) is not working in this source. 

 @Override
    public void onFaceDetection(Camera.Face[] faces, Camera camera) {
.........
}

Camera.Face[] faces is always empty.

**Comment by myoung1620** [comment]
Since this is an older comment, please let us know if you still see this issue and open a new issue.
