### ISSUE TITLE
How to play RTSP stream?

### ISSUE THREAD

**Issue by iceteahh** [WowzaMediaSystems/gocoder-sdk-samples-android#12]
I tried to build an live video chat Android application using Wowza Streaming Engine and Gocoder sdk. I have successfully published `myStream` to the Wowza server. Now I want to receive it and play it on my Android device.

I found class `WZPlayerView` in you sdk bundle. But i'm not sure how to use it.  Below is what I have tried.

```
private void playStream() {
        WZPlayerConfig playerConfig = new WZPlayerConfig();
        playerConfig.setHostAddress("192.168.1.163");
        playerConfig.setPortNumber(1935);
        playerConfig.setApplicationName("videochat");
        playerConfig.setStreamName("myStream");

        playerView.play(playerConfig, new WZStatusCallback() {
            @Override
            public void onWZStatus(WZStatus wzStatus) {
                Log.e("player", wzStatus.getState() + "");
            }

            @Override
            public void onWZError(WZStatus wzStatus) {
                Log.e("player error", wzStatus.getLastError().getErrorDescription());
            }
        });
    }
```
It seems to be not working.  Please help.

**Comment by wowza-mbrinker** [comment]
The WZPlayer requires a different license, and is currently under beta. The beta also only supports wowz protocol playback only. Pulling RTSP playback into a request for enhancement (284273).
