### ISSUE TITLE
WZH264Broadcaster examples

### ISSUE THREAD

**Issue by justintuchek** [WowzaMediaSystems/gocoder-sdk-samples-android#13]
Are there any examples of how to use the `WZH264Broadcaster`?

I am trying to broadcast video from an external camera but and I think this is what I am looking for since it uses H.264 for it's video feed data.

More of my questions are around registering a `WZSinkAPI.StreamingVideoSink` as it seems to be the only thing accepting frame data. There's 13 methods that need to be implemented but very little of them or the `WZH264Broadcaster` have any documentation around creating one other than decompiling the `WZCameraView`

**Comment by wowza-mbrinker** [comment]
Pulling this into a request (284272).
