### ISSUE TITLE
Expected receiver of type com.wowza.gocoder.sdk.sampleapp.CameraActivityBase, but got android.support.v7.widget.TintContextWrapper

### ISSUE THREAD

**Issue by ashishguptasanu** [WowzaMediaSystems/gocoder-sdk-samples-android#14]
When I click on something, I get this error every time: `Expected receiver of type com.rst.gocoder.sdk.sampleapp.CameraActivityBase, but got android.support.v7.widget.TintContextWrapper`. Anyone knows whats causing this?

**Comment by myoung1620** [comment]
You get this error by running the sample app as-is?

**Comment by myoung1620** [comment]
Please let us know in a new issue should this still be relevant today using the default sample app without modification.
