### ISSUE TITLE
the server hostname or address is not recognized

### ISSUE THREAD

**Issue by sagarmaiyad** [WowzaMediaSystems/gocoder-sdk-samples-android#15]
I got this error message while going to live streaming.

i set below details for configuration:

        goCoderBroadcastConfig!!.hostAddress = "rtmp://someaddress"
        goCoderBroadcastConfig!!.portNumber = 1935
        goCoderBroadcastConfig!!.applicationName = "live"
        goCoderBroadcastConfig!!.streamName = "myStream"

above address, port and streamname run fine while using other rtmp sample app. but its not working in it.
help me with this issue.

**Comment by manitou2k** [comment]
You need to remove that "rtmp://" part from the host address - just the IP or domain there.
