### ISSUE TITLE
mWZBroadcast.registerDataEventListener

### ISSUE THREAD

**Issue by mojtaba391** [WowzaMediaSystems/gocoder-sdk-samples-android#18]
hi.i define below code inside oncreateview for listen to server.
 WOWZBroadcast mWZBroadcast = new WOWZBroadcast();
 mWZBroadcast.registerDataEventListener("onData", new WOWZDataEvent.EventListener() {
        @Override
        public WOWZDataMap onWZDataEvent(String result, WOWZDataMap wowzDataMap) {
          Log.i("LOGGGGGGG", "result: " + result);
          return null;
        }
      });
but i can't get any data from server.plz resolve my problem
thx
![wowza2](https://user-images.githubusercontent.com/16068623/45278733-bad69100-b4e3-11e8-9a5b-13c8f7066592.png)

**Comment by jalilsedna** [comment]
I have got the same issue in a project where I receive the video but nothing happens when server sends Data.

**Comment by amirzandi** [comment]
@manitou2k @JAAulde @engineershamrock @titzi I have the same problem with my code. What is strange is that the iOS code is working like a charm but android version is not working. Please resolve this issue as soon as possible.

**Comment by amirzandi** [comment]
@manitou2k @JAAulde @engineershamrock any updates? please help!

**Comment by amirzandi** [comment]
@myoung1620 Hey Matt, do you have any idea?

**Comment by amirzandi** [comment]
@wowza-mbrinker would you please review our problem and help us?

**Comment by amirzandi** [comment]
the latest version has a bug which is reported at the issues. Hope they will review.

**Comment by Wowza-Rose** [comment]
Thank you for your patience everyone. The original person who posted this, @mojtaba391  has an open tech support ticket with Wowza and I will be sure to update you when it is resolved and share with the community.

**Comment by Wowza-Rose** [comment]
Hello, while this issue is almost completely resolved and I will update you on the full results, please do make sure you have the very latest version of GoCoder SDK downloaded for your apps to work on both iOS and Android.

**Comment by Wowza-Rose** [comment]
The latest version for iOS is 1.5.1. The latest version for Android is 1.5.0. Thank you.

**Comment by jalilsedna** [comment]
@wowza-Rose 
Hi 

Thank you for your cooperation in this regards. Im using the latest versions and cant wait to get this issue resolved as my major project deadline is very soon and my only issue outstanding is this one . I do really appreciate your help.

**Comment by Wowza-Rose** [comment]
Hello @mojtaba391 , have you resolved this issue? Feel free to update the community if it's not too much trouble. I didn't see a response from you in your customer support ticket regarding the latest download and just checking to see if everything is working ok. Thank you!

**Comment by amirzandi** [comment]
@Wowza-Rose Thank you for the great follow up. As far as you are concerned, we could eventually resolve the issue after implementing the new build of the SDK. 

Prior to close this issue, I'd strongly suggest you to resolve the aforementioned issue for others.

Thank you.

**Comment by Wowza-Rose** [comment]
Absolutely. Let me check with my team and I will comment shortly. Really appreciate your feedback!

**Comment by Wowza-Rose** [comment]
For anyone still having an issue, please submit a support ticket so we can look at your specific workflow, it can be too difficult to guess from this forum and we'd like to take a closer look at your project. We are unable to assume it's the same issue for everyone , I hope you understand. Thanks for your patience. 
https://www.wowza.com/support/open-ticket

**Comment by mojtaba391** [comment]
@Wowza-Rose Thank you for your great support and reviewing our codes.Our problem was solved in the new version
You may close this issue as well.

**Comment by akeller** [comment]
Closing per above comment.
