### ISSUE TITLE
A BUG in WOWZPlayerView

### ISSUE THREAD

**Issue by amirzandi** [WowzaMediaSystems/gocoder-sdk-samples-android#19]
It seems that there is a problem available in initializing the B value in WOWZPlayer file:
`private HashMap<String, ArrayList<EventListener>> B;`

It may leads you to a crash while sending in-stream data from server to clients. 

The iOS version is working fine unlike the Android version. 

Please resolve this issue as soon as possible.

**Comment by akeller** [comment]
Closing this as stale. If you are still experiencing the same issue with newer versions of the SDK and samples, please open a new issue.
