### ISSUE TITLE
Update WZBitmap using WZBitmap.setBitmap() got black overlayview

### ISSUE THREAD

**Issue by ghost** [WowzaMediaSystems/gocoder-sdk-samples-android#2]
I download gocoder android example and run the BitmapOverlayActivity, everything is ok but when I try to update the WZBitmap using  WZBitmap.setBitmap() like:

```
private Runnable runnable = new Runnable() {
    @Override
    public void run() {
        if (mWZBitmap != null) {
            if (System.currentTimeMillis() % 2 == 0) {
                mWZBitmap.setBitmap(overlayBitmap1);
            } else {
                mWZBitmap.setBitmap(overlayBitmap2);
            }
        }
        handler.postDelayed(runnable, 5000);
    }
};

private Handler handler = new Handler();

```

and the camera only shows black view:

![image](https://cloud.githubusercontent.com/assets/11767274/21209845/65fcd014-c2a9-11e6-9aea-ed7b06bd7275.png)

**Comment by myoung1620** [comment]
If this still occurs, please open a new issue and provide the logging.  Thanks!

**Comment by rino-a** [comment]
I managed to get this done. Please check on the following link: https://stackoverflow.com/a/51609700/1826526
