### ISSUE TITLE
 Failed to resolve: com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0@aar

### ISSUE THREAD

**Issue by Narasimham1220** [WowzaMediaSystems/gocoder-sdk-samples-android#20]
Failed to resolve: com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0@aar,  

 flatDir {
            dirs 'libs'
        }   also add in repositories

**Comment by jtpro78** [comment]
Hello,

In your build.gradle(module: app) your dependancies should look like this to install the Wowza SDK libraries:

dependencies {
implementation 'com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:2.0@aar'
...

Please also make sure that this aar file is installed in your projects lib folder.

Regards,
Jason
