### ISSUE TITLE
Failed to resolve: com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0@aar,

### ISSUE THREAD

**Issue by fahmad129** [WowzaMediaSystems/gocoder-sdk-samples-android#21]
Failed to resolve: com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.0@aar,

**Comment by rfustino** [comment]
Try this:

 compile 'com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:2.0@aar'
