### ISSUE TITLE
java.lang.RuntimeException: (set display orientation failed) at android.hardware.Camera.setDisplayOrientation(Native Method) at com.wowza.gocoder.sdk.api.devices.WOWZCamera.autoDetectOrientation(1081)

### ISSUE THREAD

**Issue by rasheedk** [WowzaMediaSystems/gocoder-sdk-samples-android#22]
java.lang.RuntimeException: (set display orientation failed)
at android.hardware.Camera.setDisplayOrientation(Native Method)
at com.wowza.gocoder.sdk.api.devices.WOWZCamera.autoDetectOrientation(1081)
at com.wowza.gocoder.sdk.api.devices.WOWZCameraView.doConfigChange(1163)
at com.wowza.gocoder.sdk.api.devices.WOWZCameraView.onConfigurationChanged(1178)
at android.app.Application.onConfigurationChanged(Application.java:114)

**- Device Info:**

Sys
Google Play Status
Services Available
Sys
Time Since App Start
>24h
Sys
App State
Active
Sys
Build Product
mido
Sys
Country
IN
Sys
CPU Architecture
aarch64
Sys
Device Locale
en_US
Sys
Device Model
Redmi Note 4
Sys
Device Sub Model
redmi note 4
Sys
Disk Space Free
16GB-32GB
Sys
Disk Size
32GB-64GB
Sys
Java Max Memory
128MB-256MB
Sys
PSS Memory
128MB-256MB
Sys
RSS Memory
<4MB
Sys
Virtual Memory
<4MB
Sys
Max Virtual Memory
<4MB
Sys
Network Status
Wifi connection
Sys
Device Orientation
Landscape
Sys
OS Version
7.0

**Go coder SDK Version**
implementation 'com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:1.6.0@aar'

**Comment by akeller** [comment]
Closing this as stale. If you are still experiencing the same issue with newer versions of the SDK and samples, please open a new issue.
