### ISSUE TITLE
FILL_VIEW in GoCoder SDK for Android works incorrectly

### ISSUE THREAD

**Issue by deepbhavsar** [WowzaMediaSystems/gocoder-sdk-samples-android#23]
I am running this demo with FILL_VIEW scale mode in Huawei P20 Pro. Android 8.0.1 device. But camera preview is stretched. Also checking in Samsung note 5.

I checked documentation from this link: https://www.wowza.com/docs/how-to-use-the-camera-view-in-gocoder-sdk-for-android  and it is like below:

> WOWZMediaConfig.FILL_VIEW | Scale the camera preview to fill the entire screen area. The preview may be cropped to maintain the aspect ratio.

It is not cropping preview for fill the screen instead of stretch preview. I stuck with it.

Please anyone help me for sort out this issue.

**Comment by akeller** [comment]
Closing this as stale. If you are still experiencing the same issue with newer versions of the SDK and samples, please open a new issue.
