### ISSUE TITLE
App crash when try to stop broadcast

### ISSUE THREAD

**Issue by Sonamgupta2109** [WowzaMediaSystems/gocoder-sdk-samples-android#3]
When i try to stop broadcast some time it crash.

STACK_TRACE=java.lang.IllegalStateException
at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
at com.wowza.gocoder.sdk.support.c.a.onDrainEncoder(GoCoderSDK:576)
at com.wowza.gocoder.sdk.support.c.a.onStopEncoding(GoCoderSDK:798)
at com.wowza.gocoder.sdk.support.c.a$a.handleMessage(GoCoderSDK:1042)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at com.wowza.gocoder.sdk.support.c.a.run(GoCoderSDK:279)
at java.lang.Thread.run(Thread.java:864)

**Comment by EitanGoldfrad** [comment]
Did you find any solution for this? @Sonamgupta2109

**Comment by myoung1620** [comment]
What version of the SDK did you test this with? Does this occur every time? If not, how often?  The crash is initiated by simply pressing the stop button?

Thanks,

Matt

**Comment by EitanGoldfrad** [comment]
Hi Matt,

For me it happened in the latest version of the SDK.

My solution was to use the ABRListener to shut down the camera when the queued buffered frames counter was too high

**Comment by myoung1620** [comment]
Thanks - we'll review this and see if we can reproduce.  Is this reproducible with the sample app from the repo or have you modified/created a new app and workflow?

**Comment by EitanGoldfrad** [comment]
You can reproduce it with the sample app, just stream high quality video on low network conditions

**Comment by myoung1620** [comment]
Ok thanks. We will work on reproducing, thanks!

**Comment by KinsukInt** [comment]
In my case the sample app crashing after 15 minutes of continuous broadcasting. I am using Gradle link 
'com.wowza.gocoder.sdk.android:com.wowza.gocoder.sdk:2.0@aar'.  I am testing in v1.0.2 build form https://www.wowza.com/resources/gocodersdk/docs/1.0/54f8721827aeb3bebffcca5e3b1a0d43/ link. Please look into it.

**Comment by akeller** [comment]
Closing this as stale. If you are still experiencing the same issue with newer versions of the SDK and samples, please open a new issue.
