### ISSUE TITLE
Timeout occured while attempting to connect

### ISSUE THREAD

**Issue by 28development** [WowzaMediaSystems/gocoder-sdk-samples-android#6]
I get this message Timeout occured while attempting to connect, I put on the correct source user + password + ip + port ...

But it somehow does not connect.

I even opened so that I do not need a source user nor a password.

But it does not work

**Comment by myoung1620** [comment]
Do you see it reaching the media server (log entries etc)?  It sounds like its not able to make the connection.

**Comment by myoung1620** [comment]
Should this still be an issue, please try reproducing using just the sample app and providing logs in a new issue.
