### ISSUE TITLE
Android Live Streaming with Sony Glass using WOWZA

### ISSUE THREAD

**Issue by harsh-special** [WowzaMediaSystems/gocoder-sdk-samples-android#7]
Hi,

I am trying to implement WOWZA with SONY GLASS in android . But I cannot find any way, how to integrate it.

Is anybody can suggest me or provide me any demo or api how to integrate it.

In Sony glass, we just get camera data in bytes, so we need such thing in wowza through which we can send our own bytes instead of WowzaGoCoder Camera 

Please guide  and help us on these task.

**Comment by wowza-mbrinker** [comment]
Pulling this into an enhancement request (284275).

**Comment by akeller** [comment]
Marked as enhancement and closing.
