### ISSUE TITLE
App freezes when stopping broadcast

### ISSUE THREAD

**Issue by PawnShop999** [WowzaMediaSystems/gocoder-sdk-samples-android#8]
Occurs more often the higher the bitrate is.
The release notes say this was fixed two versions ago, but it wasn't.

**Comment by Ganeshk365** [comment]
Yes i am also having same problem. App freeze often when call endbroadcast.

**Comment by myoung1620** [comment]
If this is still a problem, please open a new issue with some logging attached (please repo with the sample-app as-is).  We've not been able to reproduce this issue locally.
